<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Seed the Tunisian governorates and their delegations.
     *
     * Data is grouped by governorate: [governorate_fr, governorate_ar, [[name_fr, name_ar], ...]].
     * This is a working dataset covering all 24 governorates and their main delegations;
     * it can be refined later against the official INS delegation list if needed.
     */
    public function run(): void
    {
        $now = now();
        $rows = [];

        foreach ($this->data() as [$govFr, $govAr, $delegations]) {
            foreach ($delegations as [$nameFr, $nameAr]) {
                $rows[] = [
                    'name_fr' => $nameFr,
                    'name_ar' => $nameAr,
                    'governorate_fr' => $govFr,
                    'governorate_ar' => $govAr,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        foreach (array_chunk($rows, 200) as $chunk) {
            Location::insert($chunk);
        }
    }

    /**
     * @return array<int, array{0: string, 1: string, 2: array<int, array{0: string, 1: string}>}>
     */
    private function data(): array
    {
        return [
            ['Tunis', 'تونس', [
                ['Medina', 'المدينة'],
                ['Bab Bhar', 'باب بحر'],
                ['Bab Souika', 'باب سويقة'],
                ['Cité El Khadra', 'الحي الخضراء'],
                ['Djebel Jelloud', 'جبل الجلود'],
                ['El Kabaria', 'الكبارية'],
                ['El Menzah', 'المنزه'],
                ['El Omrane', 'العمران'],
                ['El Omrane Supérieur', 'العمران الأعلى'],
                ['El Ouardia', 'الوردية'],
                ['Er Ryadh', 'الرياض'],
                ['Ettahrir', 'التحرير'],
                ['Ezzouhour', 'الزهور'],
                ['Hraïria', 'الحرايرية'],
                ['La Goulette', 'حلق الوادي'],
                ['La Marsa', 'المرسى'],
                ['Le Bardo', 'باردو'],
                ['Le Kram', 'الكرم'],
                ['Séjoumi', 'السيجومي'],
                ['Sidi El Bechir', 'سيدي البشير'],
                ['Sidi Hassine', 'سيدي حسين'],
                ['Carthage', 'قرطاج'],
            ]],
            ['Ariana', 'أريانة', [
                ['Ariana Ville', 'أريانة المدينة'],
                ['Ettadhamen', 'التضامن'],
                ['Kalâat el-Andalous', 'قلعة الأندلس'],
                ['La Soukra', 'السكرة'],
                ['Mnihla', 'المنيهلة'],
                ['Raoued', 'الرواد'],
                ['Sidi Thabet', 'سيدي ثابت'],
            ]],
            ['Ben Arous', 'بن عروس', [
                ['Ben Arous', 'بن عروس'],
                ['Bou Mhel el-Bassatine', 'بومهل البساتين'],
                ['El Mourouj', 'المروج'],
                ['Ezzahra', 'الزهراء'],
                ['Fouchana', 'فوشانة'],
                ['Hammam Chott', 'حمام الشط'],
                ['Hammam Lif', 'حمام الأنف'],
                ['Medina Jedida', 'المدينة الجديدة'],
                ['Mégrine', 'مقرين'],
                ['Mohamedia', 'المحمدية'],
                ['Mornag', 'مرناق'],
                ['Radès', 'رادس'],
            ]],
            ['Manouba', 'منوبة', [
                ['Manouba', 'منوبة'],
                ['Den Den', 'دن دن'],
                ['Douar Hicher', 'دوار هيشر'],
                ['El Batan', 'البطان'],
                ['Borj El Amri', 'برج العامري'],
                ['Jedaida', 'الجديدة'],
                ['Mornaguia', 'مرناقية'],
                ['Oued Ellil', 'وادي الليل'],
                ['Tebourba', 'طبربة'],
            ]],
            ['Nabeul', 'نابل', [
                ['Nabeul', 'نابل'],
                ['Béni Khalled', 'بني خلاد'],
                ['Béni Khiar', 'بني خيار'],
                ['Bou Argoub', 'بوعرقوب'],
                ['Dar Chaabane El Fehri', 'دار شعبان الفهري'],
                ['El Haouaria', 'الهوارية'],
                ['El Mida', 'الميدة'],
                ['Grombalia', 'قرمبالية'],
                ['Hammamet', 'الحمامات'],
                ['Kelibia', 'قليبية'],
                ['Korba', 'قربة'],
                ['Menzel Bouzelfa', 'منزل بوزلفة'],
                ['Menzel Temime', 'منزل تميم'],
                ['Soliman', 'سليمان'],
                ['Takelsa', 'تاكلسة'],
            ]],
            ['Zaghouan', 'زغوان', [
                ['Zaghouan', 'زغوان'],
                ['Bir Mcherga', 'بئر مشارقة'],
                ['El Fahs', 'الفحص'],
                ['Nadhour', 'الناظور'],
                ['Saouaf', 'الصواف'],
                ['Zriba', 'الزريبة'],
            ]],
            ['Bizerte', 'بنزرت', [
                ['Bizerte Nord', 'بنزرت الشمالية'],
                ['Bizerte Sud', 'بنزرت الجنوبية'],
                ['El Alia', 'العالية'],
                ['Ghar El Melh', 'غار الملح'],
                ['Ghezala', 'غزالة'],
                ['Joumine', 'جومين'],
                ['Mateur', 'ماطر'],
                ['Menzel Bourguiba', 'منزل بورقيبة'],
                ['Menzel Jemil', 'منزل جميل'],
                ['Ras Jebel', 'رأس الجبل'],
                ['Sejnane', 'سجنان'],
                ['Tinja', 'تينجة'],
                ['Utique', 'أوتيك'],
                ['Zarzouna', 'زرزونة'],
            ]],
            ['Béja', 'باجة', [
                ['Béja Nord', 'باجة الشمالية'],
                ['Béja Sud', 'باجة الجنوبية'],
                ['Amdoun', 'عمدون'],
                ['Goubellat', 'قبلاط'],
                ['Medjez el-Bab', 'مجاز الباب'],
                ['Nefza', 'نفزة'],
                ['Téboursouk', 'تبرسق'],
                ['Testour', 'تستور'],
                ['Thibar', 'تيبار'],
            ]],
            ['Jendouba', 'جندوبة', [
                ['Jendouba', 'جندوبة'],
                ['Jendouba Nord', 'جندوبة الشمالية'],
                ['Aïn Draham', 'عين دراهم'],
                ['Balta-Bou Aouane', 'بلطة بوعوان'],
                ['Bou Salem', 'بوسالم'],
                ['Fernana', 'فرنانة'],
                ['Ghardimaou', 'غار الدماء'],
                ['Oued Meliz', 'وادي مليز'],
                ['Tabarka', 'طبرقة'],
            ]],
            ['Le Kef', 'الكاف', [
                ['Le Kef Est', 'الكاف الشرقية'],
                ['Le Kef Ouest', 'الكاف الغربية'],
                ['Dahmani', 'الدهماني'],
                ['Ebba Ksour', 'العبة قصور'],
                ['El Ksour', 'القصور'],
                ['Jérissa', 'جريصة'],
                ['Kalaat Khasba', 'قلعة خصبة'],
                ['Kalaat Senan', 'قلعة سنان'],
                ['Nebeur', 'نبر'],
                ['Sakiet Sidi Youssef', 'ساقية سيدي يوسف'],
                ['Sers', 'السرس'],
                ['Tajerouine', 'تاجروين'],
            ]],
            ['Siliana', 'سليانة', [
                ['Siliana Nord', 'سليانة الشمالية'],
                ['Siliana Sud', 'سليانة الجنوبية'],
                ['Bargou', 'برقو'],
                ['Bou Arada', 'بوعرادة'],
                ['El Aroussa', 'العروسة'],
                ['Gaâfour', 'قعفور'],
                ['Kesra', 'كسرى'],
                ['Makthar', 'مكثر'],
                ['Rouhia', 'الروحية'],
                ['Sidi Bou Rouis', 'سيدي بورويس'],
            ]],
            ['Kairouan', 'القيروان', [
                ['Kairouan Nord', 'القيروان الشمالية'],
                ['Kairouan Sud', 'القيروان الجنوبية'],
                ['Bou Hajla', 'بوحجلة'],
                ['Chebika', 'الشبيكة'],
                ['Echrarda', 'الشراردة'],
                ['El Alâa', 'العلاء'],
                ['Hajeb El Ayoun', 'حاجب العيون'],
                ['Haffouz', 'حفوز'],
                ['Nasrallah', 'نصرالله'],
                ['Oueslatia', 'الوسلاتية'],
                ['Sbikha', 'السبيخة'],
            ]],
            ['Kasserine', 'القصرين', [
                ['Kasserine Nord', 'القصرين الشمالية'],
                ['Kasserine Sud', 'القصرين الجنوبية'],
                ['Ezzouhour', 'الزهور'],
                ['El Ayoun', 'العيون'],
                ['Fériana', 'فريانة'],
                ['Foussana', 'فوسانة'],
                ['Hassi El Ferid', 'حاسي الفريد'],
                ['Hidra', 'حيدرة'],
                ['Jedelienne', 'جدليان'],
                ['Majel Bel Abbès', 'ماجل بلعباس'],
                ['Sbeitla', 'سبيطلة'],
                ['Sbiba', 'سبيبة'],
                ['Thala', 'تالة'],
            ]],
            ['Sidi Bouzid', 'سيدي بوزيد', [
                ['Sidi Bouzid Est', 'سيدي بوزيد الشرقية'],
                ['Sidi Bouzid Ouest', 'سيدي بوزيد الغربية'],
                ['Bir El Hafey', 'بئر الحفي'],
                ['Cebbala Ouled Asker', 'صبالة أولاد عسكر'],
                ['Jilma', 'جلمة'],
                ['Meknassy', 'المكناسي'],
                ['Menzel Bouzaiane', 'منزل بوزيان'],
                ['Mezzouna', 'المزونة'],
                ['Ouled Haffouz', 'أولاد حفوز'],
                ['Regueb', 'الرقاب'],
                ['Sidi Ali Ben Aoun', 'سيدي علي بن عون'],
                ['Souk Jedid', 'السوق الجديد'],
            ]],
            ['Sousse', 'سوسة', [
                ['Sousse Médina', 'سوسة المدينة'],
                ['Sousse Jawhara', 'سوسة الجوهرة'],
                ['Sousse Riadh', 'سوسة الرياض'],
                ['Sousse Sidi Abdelhamid', 'سوسة سيدي عبد الحميد'],
                ['Akouda', 'أكودة'],
                ['Bouficha', 'بوفيشة'],
                ['Enfida', 'النفيضة'],
                ['Hammam Sousse', 'حمام سوسة'],
                ['Hergla', 'هرقلة'],
                ['Kalâa Kebira', 'القلعة الكبرى'],
                ['Kalâa Seghira', 'القلعة الصغرى'],
                ['Kondar', 'القن'],
                ["M'saken", 'مساكن'],
                ['Sidi Bou Ali', 'سيدي بوعلي'],
                ['Sidi El Hani', 'سيدي الهاني'],
            ]],
            ['Monastir', 'المنستير', [
                ['Monastir', 'المنستير'],
                ['Bekalta', 'بقلطة'],
                ['Bembla', 'بنبلة'],
                ['Beni Hassen', 'بني حسان'],
                ['Jemmal', 'جمال'],
                ['Ksar Hellal', 'قصر هلال'],
                ['Ksibet el-Médiouni', 'قصيبة المديوني'],
                ['Moknine', 'المكنين'],
                ['Ouerdanine', 'الوردانين'],
                ['Sahline', 'الساحلين'],
                ['Sayada-Lamta-Bou Hajar', 'صيادة لمطة بوحجر'],
                ['Téboulba', 'طبلبة'],
                ['Zéramdine', 'زرمدين'],
            ]],
            ['Mahdia', 'المهدية', [
                ['Mahdia', 'المهدية'],
                ['Bou Merdes', 'بومرداس'],
                ['Chorbane', 'الشربان'],
                ['Chebba', 'الشابة'],
                ['El Jem', 'الجم'],
                ['Hebira', 'هبيرة'],
                ['Ksour Essef', 'قصور الساف'],
                ['Melloulèche', 'الملولش'],
                ['Ouled Chamekh', 'أولاد الشامخ'],
                ['Sidi Alouane', 'سيدي علوان'],
                ['Souassi', 'السواسي'],
            ]],
            ['Sfax', 'صفاقس', [
                ['Sfax Ville', 'صفاقس المدينة'],
                ['Sfax Ouest', 'صفاقس الغربية'],
                ['Sfax Sud', 'صفاقس الجنوبية'],
                ['Sfax Est', 'صفاقس الشرقية'],
                ['Agareb', 'عقارب'],
                ['Bir Ali Ben Khalifa', 'بئر علي بن خليفة'],
                ['El Amra', 'العامرة'],
                ['El Hencha', 'الحنشة'],
                ['Ghraiba', 'الغريبة'],
                ['Jebeniana', 'جبنيانة'],
                ['Kerkennah', 'قرقنة'],
                ['Mahres', 'المحرس'],
                ['Menzel Chaker', 'منزل شاكر'],
                ['Sakiet Eddaïer', 'ساقية الدائر'],
                ['Sakiet Ezzit', 'ساقية الزيت'],
                ['Skhira', 'الصخيرة'],
                ['Thyna', 'تينة'],
            ]],
            ['Gabès', 'قابس', [
                ['Gabès Médina', 'قابس المدينة'],
                ['Gabès Ouest', 'قابس الغربية'],
                ['Gabès Sud', 'قابس الجنوبية'],
                ['Chenini Nahal', 'شنني نحال'],
                ['El Hamma', 'الحامة'],
                ['El Metouia', 'المطوية'],
                ['Ghannouch', 'غنوش'],
                ['Mareth', 'مارث'],
                ['Matmata', 'مطماطة'],
                ['Menzel El Habib', 'منزل الحبيب'],
                ['Nouvelle Matmata', 'مطماطة الجديدة'],
                ['Oudhref', 'أوذرف'],
            ]],
            ['Médenine', 'مدنين', [
                ['Medenine Nord', 'مدنين الشمالية'],
                ['Medenine Sud', 'مدنين الجنوبية'],
                ['Ajim', 'أجيم'],
                ['Beni Khedache', 'بني خداش'],
                ['Djerba - Houmt Souk', 'جربة حومة السوق'],
                ['Djerba - Midoun', 'جربة ميدون'],
                ['Sidi Makhlouf', 'سيدي مخلوف'],
                ['Zarzis', 'جرجيس'],
            ]],
            ['Tataouine', 'تطاوين', [
                ['Tataouine Nord', 'تطاوين الشمالية'],
                ['Tataouine Sud', 'تطاوين الجنوبية'],
                ['Bir Lahmar', 'بئر الأحمر'],
                ['Dhehiba', 'الذهيبة'],
                ['Ghomrassen', 'غمراسن'],
                ['Remada', 'رمادة'],
                ['Smar', 'سمار'],
            ]],
            ['Gafsa', 'قفصة', [
                ['Gafsa Nord', 'قفصة الشمالية'],
                ['Gafsa Sud', 'قفصة الجنوبية'],
                ['Belkhir', 'بلخير'],
                ['El Guettar', 'القطار'],
                ['El Ksar', 'القصر'],
                ['Métlaoui', 'المتلوي'],
                ['Moularès', 'المولارس'],
                ['Om Larayes', 'أم العرائس'],
                ['Redeyef', 'الرديف'],
                ['Sened', 'سند'],
                ['Sidi Aïch', 'سيدي عيش'],
            ]],
            ['Tozeur', 'توزر', [
                ['Tozeur', 'توزر'],
                ['Degache', 'دقاش'],
                ['Hazoua', 'حزوة'],
                ['Nefta', 'نفطة'],
                ['Tameghza', 'تمغزة'],
            ]],
            ['Kébili', 'قبلي', [
                ['Kebili Nord', 'قبلي الشمالية'],
                ['Kebili Sud', 'قبلي الجنوبية'],
                ['Douz Nord', 'دوز الشمالية'],
                ['Douz Sud', 'دوز الجنوبية'],
                ['Faouar', 'الفوار'],
                ['Souk El Ahad', 'سوق الأحد'],
            ]],
        ];
    }
}
